# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class serviceHelloStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateCPF = channel.unary_unary(
                '/serviceHello/ValidateCPF',
                request_serializer=service__pb2.CPFRequest.SerializeToString,
                response_deserializer=service__pb2.CPFResponse.FromString,
                )
        self.ValidateCNPJ = channel.unary_unary(
                '/serviceHello/ValidateCNPJ',
                request_serializer=service__pb2.CNPJRequest.SerializeToString,
                response_deserializer=service__pb2.CNPJResponse.FromString,
                )


class serviceHelloServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateCPF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCNPJ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serviceHelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateCPF': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCPF,
                    request_deserializer=service__pb2.CPFRequest.FromString,
                    response_serializer=service__pb2.CPFResponse.SerializeToString,
            ),
            'ValidateCNPJ': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCNPJ,
                    request_deserializer=service__pb2.CNPJRequest.FromString,
                    response_serializer=service__pb2.CNPJResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serviceHello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class serviceHello(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateCPF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serviceHello/ValidateCPF',
            service__pb2.CPFRequest.SerializeToString,
            service__pb2.CPFResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateCNPJ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serviceHello/ValidateCNPJ',
            service__pb2.CNPJRequest.SerializeToString,
            service__pb2.CNPJResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
